# Generated by Django 3.1.2 on 2020-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
